name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      terraform_version:
        required: false
        description: "Enter version of Terraform to use"
        default: "1.6.6"

jobs:
  run-terraform-plan:
    uses: dilipsun/oidc-auth-workflow/.github/workflows/terraform-deploy.yml@main
    with:
      terraform_version: "${{ inputs.terraform_version }}"
    secrets: inherit


